language: python
sudo: false
python:
- '3.6'
cache:
- pip
install:
- pip install -U codecov
- pip install -r requirements-dev.txt
script:
- coverage run --source lintipy -m pytest
after_success:
- codecov
